
[server]
port = 8501
address = "0.0.0.0"
maxUploadSize = 200
enableCORS = true
enableXsrfProtection = false
headless = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#FF4B4B"
